add_newline = false
format      = "$all"

[aws]
symbol = "ï‰° "

[battery]
full_symbol        = "ï•¸"
charging_symbol    = "ï–ƒ"
discharging_symbol = "ï–‚"
format             = "[$symbol$percentage]($style) "
[[battery.display]]
style              = "bold red"
threshold          = 15
[[battery.display]]
style              = "bold yellow"
threshold          = 30

[character]
error_symbol   = "[â¯](bold red)"   # "âœ" "â–¶"
success_symbol = "[â¯](bold green)" # "âœ" "â–¶"
vicmd_symbol   = "[â®](bold green)"

[cmake]
disabled = true

[cmd_duration]
min_time = 5000

[conda]
disabled = true
symbol = "ï„Œ "

[crystal]
disabled = true

[dart]
disabled = true
symbol   = "î˜ "

[directory]
format = "[$read_only](red)[$path](bold cyan) "
read_only_symbol = "ï€£ "
truncation_symbol = "â€¦/"

[docker_context]
symbol = "ïŒˆ "

[dotnet]
disabled = true
symbol = "î¿ "

[elixir]
disabled = true
symbol   = "î‰µ "

[elm]
disabled = true
symbol   = "î˜¬ "

[erlang]
disabled = true
symbol = "î± "

[gcloud]
symbol = "ï· "

[git_branch]
format = "[(ï„¦ $branch )](bold bright-purple)"

[git_commit]
format             = "[(îœ© $hash )](bold blue)"
commit_hash_length = 8

[git_state]
format      = "[($state\\($progress_current/$progress_total\\) )](bold red)"

[git_status]
format     = "[(\\[$all_status$ahead_behind\\] )](bold yellow)"
conflicted = "=${count}"
ahead      = "â‡¡${count}"
behind     = "â‡£${count}"
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked  = "?${count}"
stashed    = "â‰¡${count}"
modified   = "!${count}"
staged     = "+${count}"
renamed    = "Â»${count}"
deleted    = "âœ˜${count}"

[golang]
symbol = "î˜§ "

[haskell]
disabled = true
symbol   = "î˜Ÿ "

[helm]
disabled = true
symbol   = "âˆ "

[hg_branch]
disabled = true
symbol   = "ï˜ "

[hostname]
trim_at = ""

[java]
disabled = true
symbol   = "î‰– "

[jobs]
symbol = "ï€“ "

[julia]
disabled = true
symbol   = "î˜¤ "

[kubernetes]
disabled = true
symbol   = "â˜¸ "

[memory_usage]
symbol = "ï¡š "

[nim]
disabled = true
symbol   = "ïš¤ "

[nix_shell]
disabled = true
symbol   = "ïŒ“ "

[nodejs]
symbol = "î˜— "

[package]
symbol = "ï£– "

[perl]
disabled = false
symbol   = "î© "

[php]
disabled = true
symbol   = "î˜ˆ "

[purescript]
disabled = true

[python]
symbol = "îœ¼ "

[ocaml]
disabled = true
symbol   = "ğŸ« "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[shlvl]
disabled = true

[singularity]
disabled = true

[status]
disabled = false
format   = "[${status}](bold red) "

[swift]
disabled = true
symbol   = "î• "

[terraform]
disabled = true
symbol   = "ğŸ’  "

[time]
disabled = true

[user]
disabled = false

[zig]
disabled = true
symbol   = "âš¡ï¸ "
