add_newline = false
format = '$all'

[aws]
disabled = true
symbol = 'ï‰° '

[battery]
full_symbol = 'ï•¸'
charging_symbol = 'ï–ƒ'
discharging_symbol = 'ï–‚'
format = '[$symbol\[$percentage\]]($style) '

[[battery.display]]
style = 'bold bright-red'
threshold = 15

[[battery.display]]
style = 'bold bright-yellow'
threshold = 30

[character]
error_symbol = '[â¯](bold bright-red)'
success_symbol = '[â¯](bold bright-green)'
vicmd_symbol = '[â®](bold bright-green)'

[cmake]
disabled = true

[cmd_duration]
min_time = 5000

[conda]
disabled = true
symbol = 'ï„Œ '

[crystal]
disabled = true

[dart]
disabled = true
symbol = 'î˜ '

[directory]
format = '[$read_only](red)[$path](bold bright-cyan) '
read_only = 'ï€£ '
truncation_symbol = 'â€¦/'

[docker_context]
symbol = 'ïŒˆ '

[dotnet]
disabled = true
symbol = 'î¿ '

[elixir]
disabled = true
symbol = 'î‰µ '

[elm]
disabled = true
symbol = 'î˜¬ '

[erlang]
disabled = true
symbol = 'î± '

[gcloud]
disabled = true
symbol = 'ï· '

[git_branch]
format = '[(ï„¦ $branch )](bold bright-purple)'

[git_commit]
format = '[(îœ© $hash)](bold bright-blue)[($tag) ](bold bright-green)'
commit_hash_length = 8
tag_disabled = false
tag_symbol = 'ï’ '

[git_state]
format = '[($state\($progress_current/$progress_total\) )](bold bright-red)'

[git_status]
format = '[(\[$all_status$ahead_behind\] )](bold bright-yellow)'
conflicted = '=${count}'
ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
untracked = '?${count}'
stashed = 'â‰¡${count}'
modified = '!${count}'
staged = '+${count}'
renamed = 'Â»${count}'
deleted = 'âœ˜${count}'

[golang]
symbol = 'î˜§ '

[helm]
disabled = true
symbol = 'âˆ '

[hg_branch]
disabled = true
symbol = 'ï˜ '

[hostname]
trim_at = ''

[java]
disabled = true
symbol = 'î‰– '

[jobs]
symbol = 'ï€“ '

[julia]
disabled = true
symbol = 'î˜¤ '

[kubernetes]
disabled = true
symbol = 'â˜¸ '

[memory_usage]
symbol = 'ï¡š '

[nim]
disabled = true
symbol = 'ïš¤ '

[nix_shell]
disabled = true
symbol = 'ïŒ“ '

[nodejs]
symbol = 'î˜— '

[package]
symbol = 'ï£– '

[perl]
disabled = false
symbol = 'î© '

[php]
disabled = true
symbol = 'î˜ˆ '

[purescript]
disabled = true

[python]
symbol = 'îœ¼ '
format = 'via [${symbol}${pyenv_prefix}(${version} )(\(${virtualenv}\) )]($style)'

[ocaml]
disabled = true
symbol = 'ğŸ« '

[ruby]
symbol = 'îˆ¾ '

[rust]
symbol = 'î¨ '

[shlvl]
disabled = true

[singularity]
disabled = true

[status]
disabled = false
format = '[${status}](bold bright-red) '

[swift]
disabled = true
symbol = 'î• '

[terraform]
disabled = true
symbol = 'ğŸ’  '

[time]
disabled = true

[username]
disabled = false

[zig]
disabled = true
symbol = 'âš¡ï¸ '
